name: Sync journal database to supabase

on:
  schedule:
    # Runs "at every 5 minute" (see https://crontab.guru)
    - cron: '*/5 * * * *'
jobs:
  build:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl https://content.indegser.com/api/journal
